# Generated by Django 3.0.3 on 2020-05-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tot_votes',
            field=models.IntegerField(default=1),
        ),
    ]
